#define TOLERANCE_PERCENTAGE 0.05F

#define MIN_TEMPERATURE 0
#define MAX_TEMPERATURE 45
#define TEMPERATURE_TOLERANCE_VALUE (MAX_TEMPERATURE * TOLERANCE_PERCENTAGE)
#define MIN_TEMPERATURE_WARNING_LEVEL (MIN_TEMPERATURE + TEMPERATURE_TOLERANCE_VALUE)
#define MAX_TEMPERATURE_WARNING_LEVEL (MAX_TEMPERATURE - TEMPERATURE_TOLERANCE_VALUE)

#define MIN_SOC 20
#define MAX_SOC 80
#define SOC_TOLERANCE_VALUE (MAX_SOC * TOLERANCE_PERCENTAGE)
#define MIN_SOC_WARNING_LEVEL (MIN_SOC + SOC_TOLERANCE_VALUE)
#define MAX_SOC_WARNING_LEVEL (MAX_SOC - SOC_TOLERANCE_VALUE)

#define MAX_CHARGERATE 0.8F
#define MAX_CHARGERATE_WARNING_LEVEL (MAX_CHARGERATE - (MAX_CHARGERATE * TOLERANCE_PERCENTAGE))


